language: node_js
cache: yarn
node_js:
  - "9"
script:
  - yarn run build
  - npm test
deploy:
  provider: npm
  email: nick@cuthbert.co.za
  api_key:
    secure: OiI28IMnf3nR4gnch8EeY9bZF5pqLzgmJBN+bmoJsBEjgOoKMMDuH2QNOlFUjiDmzWNwlVjYoQN9aGMChVubd1eRt2leeaubCJK98/6EA1TU8JkjI09dnArdrNmz+QORpofSCz3EXgg+C9obcDUMv6SdiX22KX8fuNk+i2L0sp1CSSUk6//ADdDMKLiDAUEVPSRSzuCfC3RpeSN2BL907mE9UcKq0IDaYCxrJ76+lk0gj7gXafLddGnMacvNdguiH8Ur/Y3JuTvqTHa4ZPyqsTAedrz34J++aA2yw//ci89F+HWXltL+eBSePwxEk7q8DYkRz1b98TjGApwFmwB866HwCrfP8oEJGBSUS4W6vy4PLeHsl6HSxBEMd1prtG6jADa/vvBvOTcgKlvacRG8Sl/eVoGdlbTE3iRHNXqvA8/Olsfu2Fu6HGXsZUPjAH45NzozEgygD0f6pJvz9Wa+JLmnqLd5xO6mdnJSRlRPTOw4yPaEopP6ksvJ/PHyAmVXzwMzCn0dyAtOVPqYM5C3Qtlao0/gj6GpQjwfZGQq9MrBhWjYwM6MLHrDBsTtmi8nDiJ13adx16vdOVo0O5hr06Slpyq2iTRt6I3ZkrzSrrlL+J9aQ5rW+xcYcoKv+BJSdeNu7/2BssUJR6rPxe5F0+BfNawHQ5u/7N8I9y51Kko=
  on:
    tags: true
    branch: master
    repo: reasonml-community/bs-express
